# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Type Keto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Type Keto
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Moltin', '~> 3.1'
  pod 'Stripe'

  target 'Type KetoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Type KetoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
